### ISSUE TITLE
Upload fail due to AppCenter API deprecation

### ISSUE THREAD

**Issue by VillSkog** [bitrise-steplib/steps-appcenter-deploy-ios#12]
It seems like AppCenter deprecated some APIs that are in use in this step, so the uploads now fail.

https://status.appcenter.ms/incidents/cct8ws154mnq

**Comment by ofalvai** [comment]
Hey @VillSkog, are you using the latest release of this Bitrise step? Back in December, we released version 2.0 of this step that isn't using the deprecated endpoints anymore: https://github.com/bitrise-steplib/steps-appcenter-deploy-ios/releases

**Comment by VillSkog** [comment]
> Hey @VillSkog, are you using the latest release of this Bitrise step? Back in December, we released version 2.0 of this step that isn't using the deprecated endpoints anymore: https://github.com/bitrise-steplib/steps-appcenter-deploy-ios/releases

I just checked and yes we were using the 2.0 version of the step. We switched to fastlane for the time being, but I will give another try later today then.
