### ISSUE TITLE
Release to all associated distribution groups if left blank

### ISSUE THREAD

**Issue by abelyeupear** [bitrise-steplib/steps-appcenter-deploy-ios#19]
### Issue description

Reopening https://github.com/bitrise-steplib/steps-appcenter-deploy-ios/issues/4 because AppCenter's dashboard already has a way to add the appropriate distribution groups, so with this issue we are transferring that responsibility to the Bitrise step, which shouldn't be the case.

Ideally, not setting the `distribution_group` prop just let's AppCenter decide that for you. Today, not setting this prop doesn't distribute the app to anybody.

**Comment by Roland-Bak** [comment]
Hello @abelyeupear, do you have a pull request connected to this issue? 🙂

**Comment by abelyeupear** [comment]
Nope. The previous step we used was deprecated so we were forced to move to this new one and it doesn't have the same functionality as the old one. If this were to allow AppCenter to set distribution groups, and not force to do it via this step, it would be 1:1 the deprecated step.

**Comment by abelyeupear** [comment]
Still an issue.

**Comment by ofalvai** [comment]
@abelyeupear you might be interested in the [latest release](https://github.com/bitrise-steplib/steps-appcenter-deploy-ios/releases/tag/2.2.0) where a new input was added to target all distribution groups.

**Comment by abelyeupear** [comment]
That will do! Thank you.
