### ISSUE TITLE
Release to all associated distribution groups if left blank

### ISSUE THREAD

**Issue by bencallis** [bitrise-steplib/steps-appcenter-deploy-ios#4]
I was using bitrise-step-appcenter-app-release previously and as their documentation states the option distribution_groups lets you just deploy to all associated groups if 'empty', but from this appcenter-deploy-ios step the option distribution_group does not offer the same functionality. Instead if it is left blank the app is distributed to no groups rather than all the groups the app is associated with.

Could this step be updated to include functionality to distribute to all associated app groups?

**Comment by istx25** [comment]
We happily accept pull requests. Thank you!
