### ISSUE TITLE
App Center has changed API

### ISSUE THREAD

**Issue by Kamillpg** [bitrise-steplib/steps-appcenter-deploy-ios#5]
Step not working, due to fact that App Center [has changed its API](https://github.com/microsoft/appcenter/issues/2069#issuecomment-740590121). Could someone update the URL [here](https://github.com/bitrise-steplib/steps-appcenter-deploy-ios/blob/master/vendor/github.com/bitrise-io/appcenter/app.go#L18)?

New API docs:  https://openapi.appcenter.ms/#/distribute/releases_createReleaseUpload

**Comment by istx25** [comment]
Thank you for reporting this.

**Comment by MasterLambaster** [comment]
https://github.com/bitrise-io/appcenter/pull/6 for reference, but it'll require updating vendored version and releasing new version of the step.

**Comment by bitce** [comment]
As mentioned on the pull request threads too, at this point it looks like the steps have to be reworked to use the CLI instead. We'd like to ask everyone to opt for a workaround for a short time being and use script steps to complete these submissions. (Or check out a workaround recommended here: https://github.com/bitrise-steplib/steps-appcenter-deploy-android/issues/9#issuecomment-740764770)
