### ISSUE TITLE
400 Bad Request when uploading .ipa with a space in its filename

### ISSUE THREAD

**Issue by kkizlaitis** [bitrise-steplib/steps-appcenter-deploy-ios#7]
Hello everyone!

First of all, thank you for updating the step available to accomodate the latest AppCenter API.

We have moved to this step and found one issue: our Xcode schemes contain spaces in them (for example `MyApp (Test)`, `MyApp (Production)`). The resulting .ipa file created by _Xcode Archive & Export for iOS_ step is then also named `MyApp (Test).ipa` and so on.

When uploading this .ipa file to AppCenter, this is the _POST_ request that is made (I substituted sensitive info with `<...>` from Bitrise log):
```
Uploading file with metadata:
- File name: MyApp (Test).ipa
- File size: 82586628
POST /upload/set_metadata/<...>?file_name=MyApp (Test).ipa&file_size=82586628&token=<...>
Host: file.appcenter.ms
```

which results in 400 Bad Request.

**The reason for that error is that the `file_name` is not URL encoded.** Once the file name was changed to `MyApp_Test.ipa` (not containing any spaces), the upload was successful.

Note:
For anyone having this issue, there is a workaround – in _Xcode Archive & Export for iOS_ step, under _Debug_ section, there is a field named _Generated Artifact Name_. You can change that to anything that doesn't contain a space (`MyApp`) and the resulting .ipa filename will be `MyApp.ipa`.

<img width="1016" alt="Screenshot 2021-01-07 at 16 36 56" src="https://user-images.githubusercontent.com/29122296/103904892-91a38b00-5106-11eb-8b55-b72054cc80f9.png">

**Comment by chaitanyatanna-bitrise** [comment]
Hi @kkizlaitis 
Thanks for the update on the details of the step.
We will make a note of it.

Thanks
Chaitanya

**Comment by EyMaddis** [comment]
> @trapacska pushed a commit to bitrise-io/appcenter that referenced this issue 1 hour ago

This brings us to the age old question of: Do I wait for the release or try the workaround instantly...? 👍 

Thanks for fixing this so quickly!

**Comment by chaitanyatanna-bitrise** [comment]
Hi @EyMaddis 
The fixed is released so you can update the step and then run the build.
Let me know if the build is green.

Thanks
Chaitanya

**Comment by EyMaddis** [comment]
I don't see that it is released. Github still shows 2.0.0 and my build which only requires 2.x.x still uses 2.0.0

**Comment by chaitanyatanna-bitrise** [comment]
Hi @EyMaddis 
I will check on the release with the team.
In the meantime, you can implement the workaround.

Thanks
Chaitanya

**Comment by maqoo** [comment]
I am having the same issue and still see only 2.0.0 version of the step.

**Comment by sylank** [comment]
Hi @kkizlaitis,

We have just made a step release. The release contains the filename related issue fix as well. I have marked this issue in the PR and the GitHub closed the issue after I merged the PR. We will release the steplib today and if the issue still present, please open a new issue or tag @chaitanyatanna-bitrise to re-open this ticket.

Release tag: https://github.com/bitrise-steplib/steps-appcenter-deploy-ios/releases/tag/2.0.1
Steplib PR: https://github.com/bitrise-io/bitrise-steplib/pull/2845

**Comment by kkizlaitis** [comment]
Dear @sylank , I just tried it and can confirm that the bug is gone :) Thank you!

**Comment by chaitanyatanna-bitrise** [comment]
Thank you @kkizlaitis for the confirmation. 
I will go ahead and close this issue.

Thanks
Chaitanya
